/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package milestone3;

import javax.swing.JFrame;
import milestone3.gui.MainMenu;

public class App {
    public String getGreeting() {
        return "Hello Dyrel!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MainMenu frame2 = new MainMenu();
// centre the frame on the screen
        frame2.setLocationRelativeTo(null);

// show the frame
        frame2.setVisible(true);


    }
}
