@startuml ERD-HV-LoFi 

skin rose
skinparam Style StrictUML
skinparam LineType ortho
skinparam monochrome true

class Customer {
    * customerID: Integer <<PK>>
--
    * familyName: String 
    * givenName: String
    * email: String 
    * birthDate: Date 
    * phoneNumber: Integer 
    favouriteStyle : String <<FK>>
    favouriteGenre : String <<FK>>
   * location : String 
  
}

class Sale{
    * saleID : Integer <<PK>>
    * date  : Date <<FK>>
    --
    * customerID   : Integer <<FK>>
    time : Time 
    purchaseTotal  : Double
}
class Shipment{
    * shipmentID : Integer <<PK>>
    * saleID : Integer <<FK>>
    --
    * shipmentDate : Date
    * itemQuantity : Integer
    * shipmentStatus : String
}

class Album {
    * itemType : String <<FK>>
     itemID : String <<PK>>
--
    * itemName : String <<FK>>
    * itemPrice : Double
    * genre : String <<FK>>
    //* producer : String <<FK>>
    * artist : String <<FK>>
    * year : Integer <<FK>>
    * era : String <<FK>>

}
class Item{
    * itemID : Integer <<FK>>
// * itemType: String <<FK>>
--
    * itemName : String <<FK>>
    * itemPrice : Double
    * itemYear : Integer <<FK>>
    * itemQuantity : Integer <<FK>>
    * itemDescription : String
}

class Vintage {
     itemID : Integer <<FK>>
--
    * itemName : String <<FK>>
    * itemPrice : Double
}

class ProducerAlbum {
    * producerID: Integer <<FK>>
    * albumID: String <<FK>>
}

class Producer{
    * producerID : Integer <<PK>>
--
    * producerName : String
    * producerWebsite : String
}



Sale ||..o{ Item : has
Customer ||..o{ Sale : has
Item ||..o{ Album : has
Item ||..o{ Vintage : has
Sale ||..o| Shipment : has
ProducerAlbum ||..|| Album : has
ProducerAlbum ||..|| Producer : has







@enduml 
