@startuml ERD-HV-LoFi 

skin rose
skinparam Style StrictUML
skinparam LineType ortho
skinparam monochrome true

class Customer {
    * Username: varchar <<PK>>
--
    * Family_Name : varchar 
    * Given_Name : varchar
    * Email: varchar 
    * Birth_Date : date 
    * Phone_Number : int 
    * Country : varchar 
      Favourite_Style : varchar 
      Favourite_Genre : varchar 
      DOB : date 
  
}

class Sale{
    * Sale_ID : int <<PK>>
    --
    * Date : date 
    * Buyer_ID : int <<FK>>
    * Purchase_Total : varchar
}

class SaleDetails{
    * Sale_ID : Integer <<FK>>
    * Product_ID : Integer <<FK>>
    --
    * Product_Price : varchar
    * Quantity : Integer
    * Gift_Wrapped : Boolean
}



class Music_Item{
    * Music_ID : varchar <<FK>>
--
    * Product_Type : varchar <<FK>>
    * Producer_ID : Integer <<FK>>
    * Genre : varchar 
    * Artist : varchar 
    * Year : Integer 
    * Era : varchar 
}

class Product{
    * Product_ID : Integer <<PK>>
--
    * Product_Type: varchar <<FK>>
    * Product_Name : varchar 
    * Product_Price : Double 
    * Year : Integer 
}



class Producer_Album {
    * Producer_ID: Integer <<FK>>
    * Album_ID: varchar <<FK>>
    --
    * Tracks_Produced : varchar    
}

class Producer{
    * Producer_ID : Integer <<PK>>
--
    * Producer_Name : varchar
}


class Shopping_Cart_Item {
    * Cart_ID : long <<FK>>
    * Product_ID : Integer <<FK>>
--
    * Quantity : Integer
}

class Shipping{
    * Shipping_ID : Integer <<PK>>
--
    * Shipping_Method : varchar
    * Shipping_Address : varchar
    * Shipping_Cost : Double
    * Shipping_Date : date}
}

class Store{
    * Store_ID : Integer <<PK>>
    --
    * Store_Name : varchar
    * Store_Address : varchar <<FK>>
    * Store_Phone : Integer
}
class Inventory {
    * Product_ID: Integer <<FK>>
    * Store_ID: varchar <<FK>>
    --
    * Quantity: Integer
}

class Accessory{
    * AccesoryID : varchar <<PK>>
    * productType : varchar <<FK>>
--
    *Vintage : Boolean
    *Condition : varchar
    *Signed : Boolean
    *Store_ID : Integer <<FK>>
    *Notes : varchar
}

class MusicCopy{
    * MusicCopyID : varchar <<FK>>
    * productType : varchar <<FK>>
    --
    *Tracks : Integer
    *Format : varchar
    *Version : Double
}


SaleDetails }o..|| Product 
SaleDetails }|..|| Sale 
Customer ||..o{ Sale  
Product ||..o| MusicCopy 
Music_Item ||--|{ MusicCopy

left to right direction 
Producer_Album }|..|| Music_Item  
Producer_Album }|..|| Producer  
Sale ||-o{ Shipping
Inventory }o-||Product
Inventory }o-||Store
Product ||-o| Accessory

top to bottom direction
Shopping_Cart_Item |o-|| Product
Customer ||-o{ Shopping_Cart_Item



 








@enduml 
