
GitHub Copilot prompts were considered
and used in this PlantUml diagram.
@startuml useCase



actor :Registered Customer:  as  regCust
actor :New Customer:  as  newCust

usecase (Modify Cart) as Modify
usecase (View Shopping Cart ) as View
usecase (Add item to shopping cart) as AddItem
usecase (Check out shopping cart) as Checkout
usecase (Check Payment) as Payment
usecase (Gift wrap item) as Gift
usecase (Register Customer) as Register


regCust -left- AddItem
regCust -left- View
regCust -- Modify
regCust -- Gift
regCust -- Checkout



newCust -- AddItem
newCust -- View
newCust -- Modify
newCust -left- Register
newCust -- Gift
newCust -- Checkout




AddItem ..> View : <<extends>>
View ...> Modify : <<include>>
View ..> Checkout : <<extends>>
Checkout ..> Register : <<includes>>
Checkout ..> Gift : <<extends>>
Checkout ..> Payment : <<includes>>








@endpuml 
