@startsalt ShoppingCart
skinparam BackgroundColor cornsilk

{
<size:20><b>Shopping Cart</b></size>

{+
Item | Unit Price | Quantity | Total | Remove
--|--|--|--|--
Lorem |$25.98 | ^1    ^ | $25.98 | [<&circle-x>]
Ipsum |$16.99 | ^2    ^| $33.98 | [<&circle-x>]
Dolor |$59.99| ^1    ^ | $59.99 | [<&circle-x>]
.              |       |         |  |
.              
.              |       |         |  |
.|..|...|
. 
|. |.| Total | $119.95 
.
|.|.| . |[Update]

"                         "|"          "|"        "|"          "|"         "
}
[Continue Shopping]|[Checkout]
}
@endsalt