/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package milestone3.gui;

import javax.swing.JFrame;
import milestone3.dao.ProductCollectionDAO;

/**
 *
 * @author dyrellumiwes
 */
public class MainMenu extends javax.swing.JFrame {

    ProductCollectionDAO dao = new ProductCollectionDAO();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        super();
        initComponents();
    }
        /*public MainMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }*/

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleMainMenu = new javax.swing.JLabel();
        btnAddNewProduct = new javax.swing.JButton();
        btnViewProducts = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleMainMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleMainMenu.setText("Product Catalogue");

        btnAddNewProduct.setText("Add a New Product");
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });

        btnViewProducts.setText("View Products");
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(titleMainMenu)
                    .addComponent(btnAddNewProduct)
                    .addComponent(btnViewProducts)
                    .addComponent(btnExit))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnAddNewProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        // TODO add your handling code here:
       // JFrame frame = new JFrame();
        ViewProducts dialog = new ViewProducts(this,true);

// centre the dialog on the parent window
            dialog.setLocationRelativeTo(this);

// make the dialog visible
            dialog.setVisible(true);
        
    }//GEN-LAST:event_btnViewProductsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            System.exit(0);    
            //frame.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
             // JFrame frame = new JFrame();

        AddProduct add = new AddProduct(this, true);
       add.setLocationRelativeTo(this);
       add.setVisible(true);
       
        // TODO  add your handling code here:
    }//GEN-LAST:event_btnAddNewProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JLabel titleMainMenu;
    // End of variables declaration//GEN-END:variables
}
